### ISSUE TITLE
netrunner 17.10: list of things to look into

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-related#14]
ISO tested:
http://s3-eu-central-1.amazonaws.com/ds9-eu/dci/images/1710/amd64/netrunner-desktop/netrunner-20171027.1531-amd64.hybrid.iso

- USB LIVE mode - Starting times:
-- after plymouth 1:30 minute long hang until mouse cursor appears
-- almost 3:00 minutes from mouse cursor appears to show any plasma (possibly font caching issue)
-- menu: first ever time invoking dash takes 3-4 seconds before "mouse hover" on launchers visibly works
-- calamares: takes almost a minute to start and show first "welcome screen" (used to be 6-8 seconds)

- INSTALLED Startup times:
-- 1:00 min until sddm
-- 4:00 min from sddm until plasma (possibly font cache)

- update manager:
-- 1 minute until software sources window appears (after entering password, maybe due to apt-get updating index)

- dash:
-- cannot start a program via touch (pending bug, @notmart  will look into it)
-- icon looks unsharp, previously same icon looked fine

- menu:
-- still showing iceweasel
-- showing "Hv3 web browser" entry?

- firefox:
-- clicking from one video to another on youtube mutes the ff in taskbar

**Comment by notmart** [comment]
for who has the touchscreen problem, can try the attached file (renamed to mouseeventlistener.qml) and run it with qmlscene mouseeventlistener.txt in the terminal

then try to touch the white window that comes up and see if the terminal prints out something

[mouseeventlistener.qml.txt](https://github.com/blue-systems/netrunner-related/files/1427083/mouseeventlistener.qml.txt)

**Comment by notmart** [comment]
regarding the touchscreen, maybe is driver related? i can't reproduce at all on this laptop with touchscreen here, both on the development system and on the netrunner image provided here: launching apps from dash works just fine

**Comment by notmart** [comment]
update on the test to run: new qml file to try: 
[mouseeventlistener.qml.txt](https://github.com/blue-systems/netrunner-related/files/1427172/mouseeventlistener.qml.txt)
to have qmlscene on netrunner, do apt install qmlscene beforehand.
